services:
 
  pgvector_new:
    image: pgvector/pgvector:pg17
    env_file:
      - .env.local
    container_name: pgvector_new
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pgvector: